'''
ENEMY_SPRITE_INDEX = 0
FISTS_SPRITE_INDEX = 1
CRICKET_BAT_SPRITE_INDEX = 2
KNUCKLE_DUSTER_SPRITE_INDEX = 3
SWORD_SPRITE_INDEX = 4
MINE_SPRITE_INDEX = 5
PORTAL_SPRITE_INDEX = 6
'''

SPRITE_ZOMBIE = 0
SPRITE_MINE = 1
SPRITE_GUN = 2
SPRITE_GUN_FIRE = 3
SPRITE_HEART = 4
SPRITE_GUN_ZOOM = 5
SPRITE_GUN_ZOOM_FIRE = 6
SPRITE_MINE_ITEM = 7
SPRITE_HEALTH = 8
SPRITE_GAME_OVER = 9
